WEBHOOK_PASSPHRASE = "abc123"
#Jplan3t@gmail.com 
# BYBIT_TESTNET_API_KEY = "NU4ofs44CHIBtUGnJn"
# BYBIT_TESTNET_API_SECRET = "BPlJXQWBcIlO3SADjReTAYE5SPNsPMU7mviF"

#JP3tri3@gmail.com - Main
BYBIT_TESTNET_API_KEY = "ZuEJ0HIkfMzcntVY7r"
BYBIT_TESTNET_API_SECRET = "Q5DxESJyfkptCPJcKmKD0usrex3DFuR052Kc"